//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfHost.EmployeeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllEmployee", ReplyAction="http://tempuri.org/IEmployeeService/GetAllEmployeeResponse")]
        SampleAspMvcWcfApp.Service.EmployeeResponce GetAllEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllEmployee", ReplyAction="http://tempuri.org/IEmployeeService/GetAllEmployeeResponse")]
        System.Threading.Tasks.Task<SampleAspMvcWcfApp.Service.EmployeeResponce> GetAllEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeByFirstName", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByFirstNameResponse")]
        SampleAspMvcWcfApp.Service.EmployeeResponce GetEmployeeByFirstName(string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeByFirstName", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByFirstNameResponse")]
        System.Threading.Tasks.Task<SampleAspMvcWcfApp.Service.EmployeeResponce> GetEmployeeByFirstNameAsync(string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployee", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployeeResponse")]
        void AddEmployee(SampleAspMvcWcfApp.Service.AddEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/AddEmployee", ReplyAction="http://tempuri.org/IEmployeeService/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(SampleAspMvcWcfApp.Service.AddEmployeeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : WcfHost.EmployeeService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<WcfHost.EmployeeService.IEmployeeService>, WcfHost.EmployeeService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SampleAspMvcWcfApp.Service.EmployeeResponce GetAllEmployee() {
            return base.Channel.GetAllEmployee();
        }
        
        public System.Threading.Tasks.Task<SampleAspMvcWcfApp.Service.EmployeeResponce> GetAllEmployeeAsync() {
            return base.Channel.GetAllEmployeeAsync();
        }
        
        public SampleAspMvcWcfApp.Service.EmployeeResponce GetEmployeeByFirstName(string firstName) {
            return base.Channel.GetEmployeeByFirstName(firstName);
        }
        
        public System.Threading.Tasks.Task<SampleAspMvcWcfApp.Service.EmployeeResponce> GetEmployeeByFirstNameAsync(string firstName) {
            return base.Channel.GetEmployeeByFirstNameAsync(firstName);
        }
        
        public void AddEmployee(SampleAspMvcWcfApp.Service.AddEmployeeRequest request) {
            base.Channel.AddEmployee(request);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(SampleAspMvcWcfApp.Service.AddEmployeeRequest request) {
            return base.Channel.AddEmployeeAsync(request);
        }
    }
}
